### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by superabbite1** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#7]
按教程运行最后一步的时候 报错了
`root@VM-20-7-debian:~/Auto_Install_ZtncuiForZerotier# ./Auto_Install_ZtncuiForZerotier
Traceback (most recent call last):
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 288, in main
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 41, in method_DoSubprocess
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 345, in call
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 969, in __init__
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 1778, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-16: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 311, in <module>
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 300, in main
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 41, in method_DoSubprocess
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 345, in call
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 969, in __init__
  File "/root/Auto_Install_ZtncuiForZerotier/subprocess.py", line 1778, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-13: ordinal not in range(128)
`

**Comment by TcDhlPro** [comment]
参考 #1 
设置完后, 重启服务器, 重新执行脚本即可
