### ISSUE TITLE
运行脚本第一步配置环境报错

### ISSUE THREAD

**Issue by panchenxin** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#9]
倒计时结束后没有断开ssh连接。出现如下报错：

Traceback (most recent call last):
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 311, in <module>
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 306, in main
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 132, in method_DebianCore
  File "/root/Auto_Install_ZtncuiForZerotier/Auto_Install_ZtncuiForZerotier.py", line 58, in method_GetProcessPid
IndexError: list index out of range

系统版本debian 10.10

**Comment by TcDhlPro** [comment]
进程没了,重新运行
